# -*- coding: utf-8 -*-
"""ML_Segmentacao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mj5G76p35_V4ppVpoMXDj39cTm0-kwkZ
"""

# Importando as bibliotecas
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

from google.colab import drive
drive.mount('/content/drive')

# Carregando os dados
df_dsa = pd.read_csv('dados_clientes.csv')

# Mostrando as 10 primeiras linhas
df_dsa.head(10)

df_dsa[['idade', 'renda_anual', 'pontuacao_gastos']].describe()

# Cria o padronizador dos dados
padronizador = StandardScaler()

# Aplica o padronizador apenas nas colunas de interesse
dados_padronizados = padronizador.fit_transform(df_dsa[['idade', 'renda_anual', 'pontuacao_gastos']])

print(dados_padronizados)

# Definimos o número de clusters (k)
k = 3

# Criamos o modelo K-means
kmeans = KMeans(n_clusters = k)

# Treinamento do modelo com dados padronizados
kmeans.fit(dados_padronizados)

# Atribuímos os rótulos clusters aos clientes
df_dsa['cluster'] = kmeans.labels_

# Exibe o resultado (10 primeiras linhas)
df_dsa.head(10)

df_dsa.to_csv('segmentos.csv', index=False)